name: Cold Night Checker

on:
  schedule:
    - cron: "0 9 * * *" # Jeden Tag um 10:00 Uhr MESZ (Winterzeit)
  workflow_dispatch: # Ermöglicht manuelles Ausführen

jobs:
  check-cold-night:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if API key is set
      run: |
        echo "API Key is set: ${{ secrets.OPEN_WEATHER_API }}"


    - name: Run the script
      env:
          OPEN_WEATHER_API: ${{ secrets.OPEN_WEATHER_API }}  # Injecting the secret as an environment variable
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}  # Injecting the secret as an environment variable
      run: |
        python check_cold_night.py
